apiVersion: v1
kind: Pod
metadata:
  name: jekyll-ubuntu-2013
  labels:
    name: jekyll
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command:
        - sleep
        - infinity 
