apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-centos
  name: my-centos
spec:
  containers:
  - image: my-centos:latest
    name: my-centos
    imagePullPolicy: Never
    command: ["/bin/sleep", "3650d"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
