apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-netadmin
  labels:
    name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:xenial
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
        privileged: true
      command:
        - sleep
        - infinity
        - sh
        - -c
        - apt update && apt upgrade && apt install -y wget curl iproute2 net-tools gnupg gnupg2 openssh-server
