apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      # modify
      addresses:
      - 10.0.254.11-10.0.254.20
      # up to heere
