apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: udp-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: udp-clusterrole
subjects:
- kind: ServiceAccount
  name: psp-user
  namespace: oai 
