apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: udp-psp
spec:
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedUnsafeSysctls:
  - net.core.rmem_default
  - net.core.rmem_max
  - net.core.wmem_default
  - net.core.wmem_max
