apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udp-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - udp-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
