kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nginxconfig
  labels:
    run: my-nginx-secure
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 172.16.254.1
    path: /mnt/share/nfs/pv-nginxconfig
