apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginxsecret
  labels:
    run: my-nginx-secure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
