apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx10
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: nginx10
  template:
    metadata:
      labels:
        app: nginx10
    spec:
      containers:
      - name: nginx10
        image: nginx:1.16.1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx10
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx10
  type: LoadBalancer

