apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx5
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: nginx5
  template:
    metadata:
      labels:
        app: nginx5
    spec:
      containers:
      - name: nginx5
        image: nginx:1.16.1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx5
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx5
  type: LoadBalancer
#  externalTrafficPolicy: Local


