apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx12
spec:
  replicas: 12 
  selector:
    matchLabels:
      app: nginx12
  template:
    metadata:
      labels:
        app: nginx12
    spec:
      containers:
      - name: nginx12
        image: nginx:1.16.1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx12
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx12
  type: LoadBalancer

