---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod-hoge
  annotations:
    k8s.v1.cni.cncf.io/networks: network-macvlan
    k8s.v1.cni.cncf.io/networks-status: |-  
      [{
          "name": "network-macvlan",
          "interface": "net1",
          "ips": [
              "10.0.201.2"
          ]
      }]
spec:
  containers:
  - name: centos-tools
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: worker-0
