kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast 
  nfs:
    server: 172.16.254.1
    path: /mnt/share/nfs/cassandra-3
