kind: PersistentVolume
apiVersion: v1
metadata:
  name: www-web-0 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 172.16.254.1
    path: /mnt/share/nfs/www-web-0
