apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-www-web-1
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
